### ISSUE TITLE
Publish Binaries

### ISSUE THREAD

**Issue by mattispasch** [joeferner/node-oracle#134]
Hey,
for me and others who have difficulties compiling node-oracle it would be very helpful to publish prebuilt binaries.
I looks like https://npmjs.org/package/node-pre-gyp offers a simple solution.
Thanks, Mattis

**Comment by GaryFurash** [comment]
Can we reopen this? Whenever I try to install this on a different PC (windows) I end up in Visual Studio/registry hell, endlessly trying to figure out why visual C++ isn't compiling. thanks!

**Comment by raztus** [comment]
@GaryFurash, sure, submit a pull request. None of us wanted to deal with compiling binaries for various architectures/platforms, and kontrafiktion's point was that it wouldn't alleviate making sure the Oracle libraries are in the correct path and symlinked correctly, which is likely your main headache.

**Comment by GaryFurash** [comment]
Yes.

Just curious, why is this so much more complicated than Java? If I want to connect w/ Java, i can just add a JDBC to my classpath and it's done. You can even "install" a jvm by installing it somewhere else and dragging and dropping it to the location you want.

**Comment by cjbj** [comment]
@GaryFurash If node-oracle binaries were prebuilt, installation could be similar to your Java example.  You would just drop in Instant Client and add its location to PATH (on Windows).  But as @raztus said, maintaining compiled distros is no small task. And I don't think npm is designed to support this scenario optimally.

If you have the same Node version and same OS do you need to recompile, or can you just copy your previous build to the new machine?  You could even do something like https://github.com/oracle/node-oracledb/issues/88#issuecomment-99909508 (Note this was for the other driver, node-oracledb) so that Instant Client didn't need to installed separately.

**Comment by bjouhier** [comment]
@GaryFurash 

The Java JDBC driver is provided by Oracle. It is a pure Java implementation of the Oracle wire protocol.

Several node.js database drivers are implemented with a similar appoach: wire protocol in pure JavaScript. For example, mongodb (https://github.com/mongodb/node-mongodb-native) and tedious (https://github.com/pekim/tedious). These drivers do not require any compilation step and are completely portable.

Oracle can do the same thing for its driver because they know the wire protocol. But the community cannot because the protocol is proprietary. See https://community.oracle.com/thread/615450

This driver is implemented on top of Oracle's instant client. So it is not pure JavaScript. Most of it is C++ code that does the glue between JavaScript and the instant client libraries. The scaffolding is a bit fragile because instant client only provides dynamic libraries (static linking would allow for more robust deployment). And things get really awful on windows because Visual C++ breaks binary compatibility on STL libraries between versions (see http://stackoverflow.com/questions/15836087/do-visual-studio-2012-updates-break-c-abi). So things break really bad if you mess up one of the environment variables.

Oracle is working on its own driver (https://github.com/oracle/node-oracledb). It is not yet as mature as this one but it is catching up and it is a better bet for the future. Note that this new driver is not a pure JS driver either. Like this one, it is built on top of instant client and it requires a compile step.
