### ISSUE TITLE
ORA-12154: TNS:could not resolve the connect identifier specified

### ISSUE THREAD

**Issue by thaumant** [joeferner/node-oracle#59]
Here is the code:

``` javascript
var oracle = require("oracle");
var conData = {
    tns:    '(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=myhost)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=mysid)))',
    user:   'myname',
    password: 'mypass'
};
oracle.connect(conData, function(err, con){
    if (err)
        console.log('ERROR', err);
    else
        console.log('OK', con);
});
```

And I get:

```
ERROR [Error: ORA-12154: TNS:could not resolve the connect identifier specified]
```

Connection data is correct. I have php installed with oci extension and it connects with the same copypasted connection string, username and password. SQLPlus also works.

I also tried to use:
- an object with "hostname" and "database" properties instead of "tns",
- easy connect string,
- reference to tnsnames.ora,
- random strings in all properties, like `@#$%^&*(`,
- empty object { }.

I see the same error 12154 in each case, no matter what data I put in the conData variable.

Some info about my environment:

```
ORACLE_HOME=/usr/lib/oracle/11.2/client64
OCI_INCLUDE_DIR=/usr/include/oracle/11.2/client64
OCI_LIB_DIR=/usr/lib/oracle/11.2/client64/lib
TNS_ADMIN=/usr/lib/oracle/11.2/client64/network/admin

$ uname -rvio
3.8.0-21-generic #32-Ubuntu SMP Tue May 14 22:16:46 UTC 2013 x86_64 GNU/Linux

$ node --version
v0.10.12
```

Thanks!

**Comment by rahulmykhan** [comment]
seriously, i need help.. the problem is not solved yet.
i have tried the instructions given by
https://www.youtube.com/watch?v=Sec8WG8gQPg

still, its not solved.. help me out
error: 
ora-12154 tns could not resolve service name

i am using windows 7 64 bit and oracle 11g

**Comment by Gildus** [comment]
I worked with PHP over windows and Oracle over Linux and i had the same problem, the solutions was the name of TNS different:

`oci_pconnect($opt['username'], $opt['password'], 'mytnsname', "AL32UTF8");`

And the correct is:

`oci_pconnect($opt['username'], $opt['password'], 'MYTNSNAME', "AL32UTF8");`

Because in my tnsnames.ora was for example:

```
MYTNSNAME = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)....

MYANOTHERTNSNAME = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)...
....

I hope that help somebody.

**Comment by isabolic** [comment]
I think this is because of previous installed oracle client, so if you have oracle client installed and you trying to get node.js to get connection through oracle instant client (installed python, oracle instant libs etc..) somehow "connectString" in nodejs referers to tnsnames.ora even if you remove environment variables for ORACLE_HOME, TNSNAMES etc... and add oracle instant client env. variables.. so in you connectString you should set  "local.db" instead of "local.db:1521/XE"
